[theme]
base="light"
primaryColor="#0A74DA"
backgroundColor="#FAF3E0"  # krem terang muda
secondaryBackgroundColor="#D7E9D7" # hijau muda
# secondaryBackgroundColor="#CCE6F4" # biru muda
textColor="#2E2E2E" # abu 
font="sans serif"
